services:
  compliance-dashboard:
    container_name: geyser-compliance-dashboard
    image: oven/bun:1-alpine
    # platform: linux/arm64 
    command:  sh -c "RUN_DOCKER=true && bun install && bun run dev"
    working_dir: /usr/app
    env_file: .env
    ports:
      - "3003:3003"
    networks:
      - shared-net
    restart: unless-stopped
    volumes:
      - .:/usr/app
    dns:
      - 1.1.1.1

networks:
  shared-net:
    external: true